#spring:
#  application:
#    name: auth-ms
#server:
#  port: 8082
#eureka:
#  instance:
#    preferIpAddress: true
#  renewalPercentThreshold: 0.85
#  server:
#    enableSelfPreservation: false
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka